config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  devise_for :users
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
belongs_to :user	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_action :authenticate_user!
before_action :find_product, only: [:show, :edit, :update, :destroy]
  def index
  	@products = Product.all
  end

  def new
  	@product = Product.new
  end

  def create
  	@product = current_user.products.build(product_params)
  	if @product.save
  		redirect_to root_path
  	end	
  end

  def show
  end	

  def edit
  end

  def update
  end

  def destroy
  end

  def find_product
  @product = Product.find_by(id: params[:id])
  end

  private def product_params
    params.require(:product).permit(:user_id, :title, :description, :price)	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<% if @products == [] %>
<p>There is no yet products</>
<% else %>
<% @products.each do |product| %>
<p><%= product.title %><br/>
 <%= link_to "Show it", product_path(product.id) %>
 <% end %>
  <% end %>
<p><%=  link_to  "Log in", new_user_session_path %></p>
<%=  link_to  "Log out", destroy_user_session_path, method: :delete %></br>
<% if user_signed_in? %>
 <%= link_to "Create my product", new_product_path %>
<% end %>

app/views/products/new.html.erb
<%= form_for @product, url: products_path do |product| %>
<%= product.text_field :title %>
<%= product.text_field :description %>
<%= product.text_field :price %>
<%= product.submit "Create" %>
<% end %>

app/views/products/show.html.erb
<% if user_signed_in? %>
<%=@product.title %>
<%=@product.description %>
<%=@product.price %>
<% end %>